# Generated by Django 5.1.1 on 2024-09-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_is_like_product_users_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='comments'),
        ),
    ]
