# Generated by Django 5.1.1 on 2024-10-06 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 13, 41, 44, 605587, tzinfo=datetime.timezone.utc)),
        ),
    ]
